In [1]:
import numpy as np  # Importing numpy for matrix operations

# Softmax for a single vector
def soft_max_vec(vec):
    # Convert values to probabilities (numerical stability not included here)
    return np.exp(vec) / np.sum(np.exp(vec))

# Softmax applied row-wise to a matrix
def soft_max_mat(mat):
    # Apply softmax to each row of the matrix
    return np.exp(mat) / np.sum(np.exp(mat), axis=1).reshape(-1, 1)

# Sigmoid function used in hidden layers
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [2]:
# Weight matrix from input layer (3 neurons) to first hidden layer (4 neurons)
W_1 = np.array([[2, -1, 1, 4],
                [-1, 2, -3, 1],
                [3, -2, -1, 5]])

# Weight matrix from first hidden layer (4 neurons) to second hidden layer (4 neurons)
W_2 = np.array([[3, 1, -2, 1],
                [-2, 4, 1, -4],
                [-1, -3, 2, -5],
                [3, 1, 1, 1]])

# Weight matrix from second hidden layer (4 neurons) to output layer (3 classes)
W_3 = np.array([[-1, 3, -2],
                [1, -1, -3],
                [3, -2, 2],
                [1, 2, 1]])

# Single input vector (3 input features)
x_in = np.array([0.5, 0.8, 0.2])

# Input matrix with 7 input samples (each row is one input)
x_mat_in = np.array([[0.5, 0.8, 0.2],
                     [0.1, 0.9, 0.6],
                     [0.2, 0.2, 0.3],
                     [0.6, 0.1, 0.9],
                     [0.5, 0.5, 0.4],
                     [0.9, 0.1, 0.9],
                     [0.1, 0.8, 0.7]])


In [3]:
# Function to do the neural network forward pass for one input (x_in)
def forward_single(x_in, W_1, W_2, W_3):
    # First layer: input to hidden1
    z1 = np.dot(x_in, W_1)       # shape: (4,)
    a1 = sigmoid(z1)             # apply sigmoid activation

    # Second layer: hidden1 to hidden2
    z2 = np.dot(a1, W_2)         # shape: (4,)
    a2 = sigmoid(z2)             # apply sigmoid again

    # Output layer: hidden2 to output
    z3 = np.dot(a2, W_3)         # shape: (3,) — 3 output classes
    output = soft_max_vec(z3)    # apply softmax for classification

    return output


In [4]:
# Function to process a matrix of 7 inputs (x_mat_in), each row is an input
def forward_matrix(x_mat_in, W_1, W_2, W_3):
    # First layer: input to hidden1
    z1 = np.dot(x_mat_in, W_1)   # shape: (7, 4)
    a1 = sigmoid(z1)             # apply sigmoid to each element

    # Second layer: hidden1 to hidden2
    z2 = np.dot(a1, W_2)         # shape: (7, 4)
    a2 = sigmoid(z2)             # apply sigmoid

    # Output layer: hidden2 to output
    z3 = np.dot(a2, W_3)         # shape: (7, 3)
    output = soft_max_mat(z3)    # apply softmax row-wise for classification

    return output


In [5]:
# Test the forward pass for single input
print("Output for single input (x_in):")
print(forward_single(x_in, W_1, W_2, W_3))

# Test the forward pass for multiple inputs
print("\nOutput for all 7 inputs (x_mat_in):")
print(forward_matrix(x_mat_in, W_1, W_2, W_3))


Output for single input (x_in):
[0.72780576 0.26927918 0.00291506]

Output for all 7 inputs (x_mat_in):
[[0.72780576 0.26927918 0.00291506]
 [0.62054212 0.37682531 0.00263257]
 [0.69267581 0.30361576 0.00370844]
 [0.36618794 0.63016955 0.00364252]
 [0.57199769 0.4251982  0.00280411]
 [0.38373781 0.61163804 0.00462415]
 [0.52510443 0.4725011  0.00239447]]
